### ISSUE TITLE
用不了啊老哥

### ISSUE THREAD

**Issue by menwenliang** [MoonGhost96/mask-face-recognition#1]
你是不是删错文件了，然后主文件的文件名称也修改了额

**Comment by menwenliang** [comment]
哦没事了，就主文件名称改了下，感报错是因为我的keras没下。尴尬了。感谢兄弟

**Comment by MoonGhost96** [comment]
当时交作业前改的，readme忘更新了 修复了下~

**Comment by menwenliang** [comment]
没事没事，已经用上了。就文件名改下就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MoonGhost <notifications@github.com&gt;
发送时间: 2021年1月21日 19:13
收件人: MoonGhost96/mask-face-recognition <mask-face-recognition@noreply.github.com&gt;
抄送: menwenliang <809079697@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[MoonGhost96/mask-face-recognition] 用不了啊老哥 (#1)





 
当时交作业前改的，readme忘更新了 修复了下~
